---
abstract: 'the ultimate configuration engine'
author:
  - 'Andrei Mishchenko <druxa@yandex-team.ru>'
build_requires:
  Config: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Morpheus
requires:
  DBI: 0
  Data::Dump: 0
  Data::Dumper: 0
  Digest::MD5: 0
  Exporter: 0
  File::Find: 0
  Getopt::Long: 0
  JSON: 0
  Params::Validate: 0
  Pod::Usage: 0
  Symbol: 0
  Template: 0
  XML::Simple: 0
  base: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/druxa/morpheus/issues
  homepage: http://github.com/druxa/morpheus/wiki
  repository: git://github.com/druxa/morpheus.git
version: 0.46
